### ISSUE TITLE
2.26a.2.output (valószínűleg duplikált a feltöltés)

### ISSUE THREAD

**Issue by Mordai** [flugi/bp1_feladatok#11]
A 2.26a.1.output megegyezik a 2.26a.2.output-tal, valószínűleg véletlen ugyan azt töltötted fel a 2.26a2-es inputhoz.
A 13 prímtényezős felbontása 1•13, és nem 2•2•7, ami egyébként a 2.26a.1.output-ban is megtalálható. 😊
(Egyébként Mészöly Marcell vette észre, köszi neki!)

**Comment by flugi** [comment]
javítva - (Köllőd Csaba résen volt és évkezdés előtt megpingelte a helyzetet, mindig beleszorultunk abba, hogy hát már volt aki úgy töltötte fel, most már akkor hagyjuk....)
